### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by kireoxdz** [tau-yihouxiang/X-Ray#1]
I am a new researcher, Could you please send me One sample case? My network is not good. I want to see the sample so that I can make my own data set. Thank you. This is my email address "1196345479@qq.com"

**Comment by tau-yihouxiang** [comment]
Thank you for your interesting. I have pushed an example dataset in ./example folder so that you can try to train and check the data structure.

**Comment by kireoxdz** [comment]
@tau-yihouxiang Thank you so much! Another question, do you have the data sets of ’‘objaverse-xl’‘  and ’‘objaverse-1.0’‘? Can you provide me with a case for each? The original data is too large to download.

**Comment by tau-yihouxiang** [comment]
I processed the data from objaverse-1.0 dataset, you can download them from their UUID: 0a0bc2921e5246a28732bf5584c251d1 / 0a0bec73aeb9466e875ae760fd75e64a / 0a0c75dab0844e7fa5b299d4af858bec

**Comment by kireoxdz** [comment]
@tau-yihouxiang Thanks for your help
